In [97]:
#phase 1
# 1.	Import Pandas and load the Online Retail Excel dataset into a DataFrame named df.
# 2.	Display the first 5 transaction records and identify what each row represents.
# 3.	Display the last 10 records and inspect whether the final transactions look structurally consistent.
# 4.	Display 15 randomly selected transaction records to understand the variety of data.
# 5.	Print the total number of rows and columns in the dataset.
# 6.	Display all column names and identify the columns needed to analyze revenue.
# 7.	Display the data type of every column and identify any unsuitable data types.
# 8.	Determine how many rows and columns the original dataset contains.
# 9.	Display the first 20 product descriptions and identify examples of different products.
# 10.	Write a short business summary explaining what the dataset contains and what the company wants to learn.

import pandas as pd

In [3]:
data=pd.read_csv("online_retail_practice_sample.csv")
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [4]:
data.shape

(1612, 8)

In [5]:
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

In [6]:
data.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1604,565607,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2011-07-24 17:52:00,2.71,13346.0,Netherlands
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [7]:
data.sample(15,random_state=42)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
29,565045,22752,SET 7 BABUSHKA NESTING BOXES,8,2011-10-05 07:59:00,7.65,17321.0,Netherlands
259,544497,POST,POSTAGE,2,2010-12-10 14:46:00,21.60,15411.0,France
383,539123,71053,WHITE METAL LANTERN,12,2011-02-09 04:06:00,4.07,14097.0,France
425,565669,79323P,PINK CHERRY LIGHTS,14,2011-07-13 11:38:00,5.40,14394.0,EIRE
239,559785,71053,WHITE METAL LANTERN,8,2011-08-20 18:01:00,4.07,17429.0,Sweden
787,562769,21977,PACK OF 60 PINK PAISLEY CAKE CASES,11,2011-03-16 12:30:00,0.66,12969.0,Australia
1471,544897,21977,PACK OF 60 PINK PAISLEY CAKE CASES,8,2011-07-18 18:26:00,0.55,18175.0,Portugal
497,561669,21730,GLASS STAR FROSTED T-LIGHT HOLDER,8,2011-02-01 01:20:00,4.25,14894.0,Spain
495,566207,21212,PACK OF 72 RETROSPOT CAKE CASES,11,2011-08-29 00:28:00,0.55,14557.0,France
754,568872,84406B,CREAM CUPID HEARTS COAT HANGER,12,2011-09-12 09:05:00,3.30,14377.0,United Kingdom
411,572532,21977,PACK OF 60 PINK PAISLEY CAKE CASES,1,2011-07-20 17:18:00,0.55,16634.0,Germany
1581,552090,21730,GLASS STAR FROSTED T-LIGHT HOLDER,9,2011-01-19 21:03:00,5.10,13181.0,France
720,C537033,22752,SET 7 BABUSHKA NESTING BOXES,-5,2011-08-03 23:56:00,7.65,16639.0,United Kingdom
247,576014,85123A,WHITE HANGING HEART T-LIGHT HOLDER,5,2011-06-11 17:56:00,2.04,12691.0,United Kingdom
567,547774,79323P,PINK CHERRY LIGHTS,13,2011-01-24 11:59:00,5.40,14055.0,Netherlands

In [10]:
print(data.shape[0])
print(data.shape[1])

1612
8

In [14]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [16]:
data.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [17]:
data.ndim

2

In [21]:
rows, columns = data.shape
print(rows)
print(columns)

1612
8

In [24]:
data['Description'].head(20)

0                     WHITE METAL LANTERN
1       GLASS STAR FROSTED T-LIGHT HOLDER
2     KNITTED UNION FLAG HOT WATER BOTTLE
3                     WHITE METAL LANTERN
4     KNITTED UNION FLAG HOT WATER BOTTLE
5     KNITTED UNION FLAG HOT WATER BOTTLE
6                                 POSTAGE
7                                 POSTAGE
8      PACK OF 60 PINK PAISLEY CAKE CASES
9                     WHITE METAL LANTERN
10                 HAND WARMER UNION JACK
11        PACK OF 72 RETROSPOT CAKE CASES
12                                POSTAGE
13           SET 7 BABUSHKA NESTING BOXES
14      GLASS STAR FROSTED T-LIGHT HOLDER
15     PACK OF 60 PINK PAISLEY CAKE CASES
16                                POSTAGE
17               REGENCY CAKESTAND 3 TIER
18                     PINK CHERRY LIGHTS
19               REGENCY CAKESTAND 3 TIER
Name: Description, dtype: str

In [27]:
#phase 2
# 11.	Create a separate DataFrame containing only InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID and Country.
# 12.	Create a small DataFrame containing the first 10 transactions and save it as a separate variable.
# 13.	Generate descriptive statistics for numerical columns and explain what Quantity and UnitPrice reveal.
# 14.	Generate descriptive summaries for categorical columns such as Country and Description.
# 15.	Display detailed DataFrame information and identify columns with missing entries.
# 16.	Determine the number of distinct invoice numbers, products, countries and identified customers.
# 17.	Display the unique values in Country and determine how many countries appear in the dataset.
# 18.	Count transactions recorded for each country and display the 10 most frequent countries.
# 19.	Create a compact dataset summary containing row count, column count, unique products and unique invoices.
# 20.	Export a basic dataset profile to a CSV file for documentation.

data[[
    "InvoiceNo", "StockCode", "Description",
    "Quantity", "UnitPrice", "CustomerID", "Country"
]]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17296.0,Germany

In [29]:
a=data.head(10)
print(a)

  InvoiceNo StockCode                          Description  Quantity  \
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
2    545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         0
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
5    561166    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         3
6    570510      POST                              POSTAGE         4
7    574557      POST                              POSTAGE         1
8    572698     21977   PACK OF 60 PINK PAISLEY CAKE CASES         2
9    547022     71053                  WHITE METAL LANTERN         7

           InvoiceDate  UnitPrice  CustomerID         Country
0  2011-09-15 15:26:00       4.07     16640.0          Sweden
1  2011-06-05 08:10:00       4.25     17154.0          Sweden
2  2011-07-24 03:45:00       3.39     16783.0     Netherlands
3  2011-09-04 16:55:00       3.39     14222.0           Spain
4  2011-02-23 13:40:00       3.39     16830.0          Sweden
5  2011-02-28 16:38:00       4.07     12343.0           Spain
6  2011-07-01 00:08:00      14.40     12767.0  United Kingdom
7  2011-09-23 07:36:00      21.60     13566.0          France
8  2011-03-20 10:39:00       0.55     14765.0         Germany
9  2011-09-14 17:41:00       4.07     15256.0            EIRE

In [31]:
data.describe()

          Quantity    UnitPrice    CustomerID
count  1612.000000  1612.000000   1541.000000
mean      7.158189     5.523189  15201.415315
std       5.890089     5.191564   1693.230069
min     -15.000000     0.000000  12305.000000
25%       4.000000     2.200000  13708.000000
50%       8.000000     3.390000  15220.000000
75%      12.000000     7.650000  16640.000000
max      15.000000    21.600000  18196.000000

In [33]:
data[['Country','Description']].describe()

       Country Description
count     1599        1589
unique      10          22
top     France     POSTAGE
freq       178         143

In [34]:
data.info

<bound method DataFrame.info of      InvoiceNo StockCode                          Description  Quantity  \
0       570338     71053                  WHITE METAL LANTERN         7
1       574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
2       545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         0
3       567005     71053                  WHITE METAL LANTERN        12
4       573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
...        ...       ...                                  ...       ...
1607    546730     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
1608    556479     22423             REGENCY CAKESTAND 3 TIER        13
1609   C541876     21730    GLASS STAR FROSTED T-LIGHT HOLDER        -7
1610    553299    85123A   WHITE HANGING HEART T-LIGHT HOLDER         8
1611    537515    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6

              InvoiceDate  UnitPrice  CustomerID      Country
0     2011-09-15 15:26:00       4.07     16640.0       Sweden
1     2011-06-05 08:10:00       4.25     17154.0       Sweden
2     2011-07-24 03:45:00       3.39     16783.0  Netherlands
3     2011-09-04 16:55:00       3.39     14222.0        Spain
4     2011-02-23 13:40:00       3.39     16830.0       Sweden
...                   ...        ...         ...          ...
1607  2011-09-20 00:21:00       4.25     16326.0        Spain
1608  2011-11-13 09:05:00      12.75     13615.0         EIRE
1609  2011-04-07 12:48:00       5.10     16943.0        Spain
1610  2011-09-24 16:24:00       2.55     17478.0     Portugal
1611  2011-08-24 00:48:00       2.55     17296.0      Germany

[1612 rows x 8 columns]>

In [41]:
data[data.notnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [49]:
print(data['InvoiceNo'].nunique())
print(data['StockCode'].nunique())
print(data['Country'].nunique())
print(data['CustomerID'].nunique())

1574
12
10
1346

In [57]:
country=data['Country'].dropna().unique()
print(country)
len(country)

<ArrowStringArray>
[        'Sweden',    'Netherlands',          'Spain', 'United Kingdom',
         'France',        'Germany',           'EIRE',       'Portugal',
        'Belgium',      'Australia']
Length: 10, dtype: str

10

In [64]:
count=data['Country'].value_counts()
count.head(10)

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [65]:
summary = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Unique Products",
        "Unique Invoices"
    ],
    "Value": [
        data.shape[0],
        data.shape[1],
        data["StockCode"].nunique(),
        data["InvoiceNo"].nunique()
    ]
})

print(summary)

            Metric  Value
0       Total Rows   1612
1    Total Columns      8
2  Unique Products     12
3  Unique Invoices   1574

In [66]:
#phase 3
# 21.	Select and display only InvoiceNo and InvoiceDate for all transactions.
# 22.	Retrieve a transaction at a specified row position using iloc and explain the difference between row position and index label.
# 23.	Use loc to retrieve selected columns for a chosen range of index labels.
# 24.	Filter transactions where Quantity is greater than 10.
# 25.	Find transactions where UnitPrice is greater than £50.
# 26.	Retrieve all transactions belonging to a specified country using a Boolean condition.
# 27.	Use isin to find transactions from the five countries with the highest transaction counts.
# 28.	Use between to retrieve transactions with quantities between 5 and 20 inclusive.
# 29.	Use query to find transactions where Quantity is greater than 10 and UnitPrice is greater than £5.
# 30.	Sort transactions by UnitPrice in descending order and display the 20 highest unit-price records.

data[["InvoiceNo", "InvoiceDate"]]

     InvoiceNo          InvoiceDate
0       570338  2011-09-15 15:26:00
1       574674  2011-06-05 08:10:00
2       545052  2011-07-24 03:45:00
3       567005  2011-09-04 16:55:00
4       573512  2011-02-23 13:40:00
...        ...                  ...
1607    546730  2011-09-20 00:21:00
1608    556479  2011-11-13 09:05:00
1609   C541876  2011-04-07 12:48:00
1610    553299  2011-09-24 16:24:00
1611    537515  2011-08-24 00:48:00

[1612 rows x 2 columns]

In [67]:
data.iloc[5]

InvoiceNo                                   561166
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                         3
InvoiceDate                    2011-02-28 16:38:00
UnitPrice                                     4.07
CustomerID                                 12343.0
Country                                      Spain
Name: 5, dtype: object

In [73]:
data.loc[0:10,['InvoiceNo','Description','Quantity']]

   InvoiceNo                          Description  Quantity
0     570338                  WHITE METAL LANTERN         7
1     574674    GLASS STAR FROSTED T-LIGHT HOLDER        14
2     545052  KNITTED UNION FLAG HOT WATER BOTTLE         0
3     567005                  WHITE METAL LANTERN        12
4     573512  KNITTED UNION FLAG HOT WATER BOTTLE        15
5     561166  KNITTED UNION FLAG HOT WATER BOTTLE         3
6     570510                              POSTAGE         4
7     574557                              POSTAGE         1
8     572698   PACK OF 60 PINK PAISLEY CAKE CASES         2
9     547022                  WHITE METAL LANTERN         7
10    567596               HAND WARMER UNION JACK        15

In [74]:
data[data['Quantity']>10]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
10,567596,22633,HAND WARMER UNION JACK,15,2011-07-24 14:21:00,1.68,15220.0,France
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
...,...,...,...,...,...,...,...,...
1593,560762,21730,GLASS STAR FROSTED T-LIGHT HOLDER,11,2011-07-22 02:33:00,4.25,15530.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

In [77]:
data[data['UnitPrice']>50]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [78]:
data[data["Country"] == "United Kingdom"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6,570510,POST,POSTAGE,4,2011-07-01 00:08:00,14.40,12767.0,United Kingdom
42,575608,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,8,2011-05-14 00:18:00,4.07,12560.0,United Kingdom
69,566686,22423,REGENCY CAKESTAND 3 TIER,13,2011-06-14 08:46:00,12.75,15782.0,United Kingdom
71,561128,22633,HAND WARMER UNION JACK,6,2011-09-01 14:03:00,2.10,15231.0,United Kingdom
79,557907,22423,REGENCY CAKESTAND 3 TIER,5,2011-06-16 06:13:00,15.30,15131.0,United Kingdom
...,...,...,...,...,...,...,...,...
1566,540156,POST,POSTAGE,1,2011-02-17 08:49:00,18.00,14542.0,United Kingdom
1571,575154,POST,POSTAGE,8,2011-05-14 16:00:00,18.00,14689.0,United Kingdom
1583,574808,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,5,2010-12-10 10:43:00,4.07,16508.0,United Kingdom
1598,567397,71053,WHITE METAL LANTERN,8,2011-03-13 19:34:00,3.39,17260.0,United Kingdom
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom

In [79]:
top5 = data["Country"].value_counts().head(5).index

result = data[data["Country"].isin(top5)]

print(result)

     InvoiceNo StockCode                          Description  Quantity  \
0       570338     71053                  WHITE METAL LANTERN         7
1       574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
3       567005     71053                  WHITE METAL LANTERN        12
4       573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
5       561166    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         3
...        ...       ...                                  ...       ...
1602    576798     22633               HAND WARMER UNION JACK         8
1605    569476     22423             REGENCY CAKESTAND 3 TIER         4
1606   C554322     21212      PACK OF 72 RETROSPOT CAKE CASES        -6
1607    546730     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
1609   C541876     21730    GLASS STAR FROSTED T-LIGHT HOLDER        -7

              InvoiceDate  UnitPrice  CustomerID    Country
0     2011-09-15 15:26:00       4.07     16640.0     Sweden
1     2011-06-05 08:10:00       4.25     17154.0     Sweden
3     2011-09-04 16:55:00       3.39     14222.0      Spain
4     2011-02-23 13:40:00       3.39     16830.0     Sweden
5     2011-02-28 16:38:00       4.07     12343.0      Spain
...                   ...        ...         ...        ...
1602  2011-03-20 15:46:00       2.10     16068.0  Australia
1605  2011-04-19 21:53:00      12.75     17314.0     Sweden
1606  2011-08-16 02:22:00       0.55     18187.0     Sweden
1607  2011-09-20 00:21:00       4.25     16326.0      Spain
1609  2011-04-07 12:48:00       5.10     16943.0      Spain

[834 rows x 8 columns]

In [80]:
data[data["Quantity"].between(5, 20)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
9,547022,71053,WHITE METAL LANTERN,7,2011-09-14 17:41:00,4.07,15256.0,EIRE
...,...,...,...,...,...,...,...,...
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [81]:
data.query("Quantity > 10 and UnitPrice > 5")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
31,550785,22423,REGENCY CAKESTAND 3 TIER,15,2011-09-25 21:14:00,12.75,16898.0,Netherlands
38,566325,22423,REGENCY CAKESTAND 3 TIER,11,2011-01-14 18:07:00,10.20,13528.0,Sweden
69,566686,22423,REGENCY CAKESTAND 3 TIER,13,2011-06-14 08:46:00,12.75,15782.0,United Kingdom
89,577425,22752,SET 7 BABUSHKA NESTING BOXES,14,2011-11-16 02:46:00,6.12,16327.0,Sweden
...,...,...,...,...,...,...,...,...
1575,547919,22423,REGENCY CAKESTAND 3 TIER,11,2011-04-09 18:38:00,12.75,16277.0,EIRE
1587,572765,21730,GLASS STAR FROSTED T-LIGHT HOLDER,15,2010-12-12 17:20:00,5.10,17421.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

In [82]:
data.sort_values(
    by="UnitPrice",
    ascending=False
).head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1248,565100,POST,POSTAGE,14,2011-11-25 20:27:00,21.6,13873.0,Australia
1253,573477,POST,POSTAGE,8,2011-04-22 14:47:00,21.6,18172.0,EIRE
49,557529,POST,POSTAGE,7,2011-08-19 06:38:00,21.6,17690.0,Australia
465,569506,POST,POSTAGE,6,2011-11-08 11:22:00,21.6,16513.0,Australia
932,C561717,POST,POSTAGE,-11,2011-11-22 12:10:00,21.6,15675.0,Netherlands
1528,565108,POST,POSTAGE,10,2011-03-29 08:51:00,21.6,16176.0,France
1560,567925,POST,POSTAGE,4,2011-01-20 13:21:00,21.6,17041.0,France
101,573603,POST,POSTAGE,8,2011-03-16 11:27:00,21.6,14863.0,Australia
764,572968,POST,POSTAGE,6,2011-07-22 19:28:00,21.6,16251.0,Germany
502,C543573,POST,POSTAGE,-15,2011-05-26 09:37:00,21.6,17799.0,Spain
833,574836,POST,POSTAGE,2,2011-05-21 21:25:00,21.6,14562.0,EIRE
501,552616,POST,POSTAGE,6,2011-05-15 13:37:00,21.6,12473.0,France
752,549960,POST,POSTAGE,15,2011-10-20 05:17:00,21.6,14865.0,Australia
353,570905,POST,POSTAGE,12,2011-05-18 16:49:00,21.6,NaN,United Kingdom
359,547600,POST,POSTAGE,8,2011-10-08 10:31:00,21.6,14477.0,Portugal
456,578392,POST,POSTAGE,1,2010-12-16 14:40:00,21.6,15550.0,Germany
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.6,13566.0,France
617,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
893,565522,POST,POSTAGE,1,2011-08-02 16:33:00,21.6,13623.0,United Kingdom

In [83]:
#phase 4
# 31.	Create a working copy of the original DataFrame and retain the untouched source as df_raw.
# 32.	Rename the Description column to ProductDescription in your working copy.
# 33.	Create a Revenue column by multiplying Quantity by UnitPrice, preserving the original signed quantity.
# 34.	Create a TransactionType column to classify records as cancellation, return, positive sale or other/invalid, using documented rules.
# 35.	Create an IsIdentifiedCustomer column that indicates whether CustomerID is available.
# 36.	Convert InvoiceDate to a proper Pandas datetime data type.
# 37.	Convert InvoiceNo, StockCode and Country to suitable string data types.
# 38.	Reorder columns so transaction identifiers and dates appear before product, customer and financial information.
# 39.	Sort the working dataset by InvoiceDate and then by InvoiceNo.
# 40.	Reset the DataFrame index after sorting and verify that the new index is sequential.

In [86]:
data.rename(
    columns={"Description": "ProductDescription"},
    inplace=True
)

print(data.columns)

Index(['InvoiceNo', 'StockCode', 'ProductDescription', 'Quantity',
       'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [87]:
data["Revenue"] = data["Quantity"] * data["UnitPrice"]

print(data[["Quantity", "UnitPrice", "Revenue"]].head())

   Quantity  UnitPrice  Revenue
0         7       4.07    28.49
1        14       4.25    59.50
2         0       3.39     0.00
3        12       3.39    40.68
4        15       3.39    50.85

In [89]:
import numpy as np
conditions = [
    data["InvoiceNo"].str.startswith("C", na=False),
    data["Quantity"] < 0,
    (data["Quantity"] > 0) & (data["UnitPrice"] > 0)
]

choices = ["Cancellation", "Return", "Positive sale"]

data["TransactionType"] = np.select(
    conditions,
    choices,
    default="Other/invalid"
)

print(data[["InvoiceNo", "Quantity", "UnitPrice", "TransactionType"]])

     InvoiceNo  Quantity  UnitPrice TransactionType
0       570338         7       4.07   Positive sale
1       574674        14       4.25   Positive sale
2       545052         0       3.39   Other/invalid
3       567005        12       3.39   Positive sale
4       573512        15       3.39   Positive sale
...        ...       ...        ...             ...
1607    546730        14       4.25   Positive sale
1608    556479        13      12.75   Positive sale
1609   C541876        -7       5.10    Cancellation
1610    553299         8       2.55   Positive sale
1611    537515         6       2.55   Positive sale

[1612 rows x 4 columns]

In [90]:
data["IsIdentifiedCustomer"] = data["CustomerID"].notna()

print(data[["CustomerID", "IsIdentifiedCustomer"]])

      CustomerID  IsIdentifiedCustomer
0        16640.0                  True
1        17154.0                  True
2        16783.0                  True
3        14222.0                  True
4        16830.0                  True
...          ...                   ...
1607     16326.0                  True
1608     13615.0                  True
1609     16943.0                  True
1610     17478.0                  True
1611     17296.0                  True

[1612 rows x 2 columns]

In [91]:
data["InvoiceDate"] = pd.to_datetime(
    data["InvoiceDate"],
    errors="coerce"
)

print(data["InvoiceDate"])
print(data["InvoiceDate"].dtype)

0      2011-09-15 15:26:00
1      2011-06-05 08:10:00
2      2011-07-24 03:45:00
3      2011-09-04 16:55:00
4      2011-02-23 13:40:00
               ...
1607   2011-09-20 00:21:00
1608   2011-11-13 09:05:00
1609   2011-04-07 12:48:00
1610   2011-09-24 16:24:00
1611   2011-08-24 00:48:00
Name: InvoiceDate, Length: 1612, dtype: datetime64[us]
datetime64[us]

In [92]:
data["InvoiceNo"] = data["InvoiceNo"].astype("string")
data["StockCode"] = data["StockCode"].astype("string")
data["Country"] = data["Country"].astype("string")

print(data[["InvoiceNo", "StockCode", "Country"]].dtypes)

InvoiceNo    string
StockCode    string
Country      string
dtype: object

In [93]:
data = data[[
    "InvoiceNo",
    "InvoiceDate",
    "StockCode",
    "ProductDescription",
    "CustomerID",
    "Country",
    "Quantity",
    "UnitPrice",
    "Revenue",
    "TransactionType",
    "IsIdentifiedCustomer"
]]

print(data.head())

  InvoiceNo         InvoiceDate StockCode  \
0    570338 2011-09-15 15:26:00     71053
1    574674 2011-06-05 08:10:00     21730
2    545052 2011-07-24 03:45:00    84029G
3    567005 2011-09-04 16:55:00     71053
4    573512 2011-02-23 13:40:00    84029G

                    ProductDescription  CustomerID      Country  Quantity  \
0                  WHITE METAL LANTERN     16640.0       Sweden         7
1    GLASS STAR FROSTED T-LIGHT HOLDER     17154.0       Sweden        14
2  KNITTED UNION FLAG HOT WATER BOTTLE     16783.0  Netherlands         0
3                  WHITE METAL LANTERN     14222.0        Spain        12
4  KNITTED UNION FLAG HOT WATER BOTTLE     16830.0       Sweden        15

   UnitPrice  Revenue TransactionType  IsIdentifiedCustomer
0       4.07    28.49   Positive sale                  True
1       4.25    59.50   Positive sale                  True
2       3.39     0.00   Other/invalid                  True
3       3.39    40.68   Positive sale                  True
4       3.39    50.85   Positive sale                  True

In [94]:
data = data.sort_values(
    by=["InvoiceDate", "InvoiceNo"],
    ascending=[True, True]
)

print(data)

     InvoiceNo         InvoiceDate StockCode  \
1523    569444 2010-12-01 00:05:00     71053
122    C543863 2010-12-01 02:26:00    84406B
409     568184 2010-12-01 03:57:00    84406B
78     C551232 2010-12-01 06:06:00     71053
1312    536850 2010-12-01 21:38:00     22423
...        ...                 ...       ...
1532    558153 2011-12-08 04:14:00    84406B
831     542017 2011-12-08 06:50:00    85123A
1161    544435 2011-12-08 07:15:00     21730
801     572572 2011-12-08 17:37:00    79323P
21      579630 2011-12-08 18:19:00    84029G

                       ProductDescription  CustomerID      Country  Quantity  \
1523                  WHITE METAL LANTERN     13845.0      Germany        15
122        CREAM CUPID HEARTS COAT HANGER     14319.0       France       -13
409        CREAM CUPID HEARTS COAT HANGER     15058.0       France         3
78                    WHITE METAL LANTERN     12472.0        Spain        -7
1312             REGENCY CAKESTAND 3 TIER     12972.0       Sweden         9
...                                   ...         ...          ...       ...
1532       CREAM CUPID HEARTS COAT HANGER     12313.0       Sweden         8
831    WHITE HANGING HEART T-LIGHT HOLDER     13029.0       France         2
1161    GLASS STAR FROSTED T-LIGHT HOLDER     15446.0  Netherlands         6
801                    PINK CHERRY LIGHTS     12426.0      Belgium         5
21    KNITTED UNION FLAG HOT WATER BOTTLE     13148.0      Germany        15

      UnitPrice  Revenue TransactionType  IsIdentifiedCustomer
1523       3.39    50.85   Positive sale                  True
122        2.75   -35.75    Cancellation                  True
409        2.20     6.60   Positive sale                  True
78         4.07   -28.49    Cancellation                  True
1312      10.20    91.80   Positive sale                  True
...         ...      ...             ...                   ...
1532       2.75    22.00   Positive sale                  True
831        3.06     6.12   Positive sale                  True
1161       5.10    30.60   Positive sale                  True
801        6.75    33.75   Positive sale                  True
21         3.39    50.85   Positive sale                  True

[1612 rows x 11 columns]

In [95]:
data = data.reset_index(drop=True)

print(data)
print("Index:", data.index.tolist())
print("Sequential index:", data.index.equals(pd.RangeIndex(len(data))))

     InvoiceNo         InvoiceDate StockCode  \
0       569444 2010-12-01 00:05:00     71053
1      C543863 2010-12-01 02:26:00    84406B
2       568184 2010-12-01 03:57:00    84406B
3      C551232 2010-12-01 06:06:00     71053
4       536850 2010-12-01 21:38:00     22423
...        ...                 ...       ...
1607    558153 2011-12-08 04:14:00    84406B
1608    542017 2011-12-08 06:50:00    85123A
1609    544435 2011-12-08 07:15:00     21730
1610    572572 2011-12-08 17:37:00    79323P
1611    579630 2011-12-08 18:19:00    84029G

                       ProductDescription  CustomerID      Country  Quantity  \
0                     WHITE METAL LANTERN     13845.0      Germany        15
1          CREAM CUPID HEARTS COAT HANGER     14319.0       France       -13
2          CREAM CUPID HEARTS COAT HANGER     15058.0       France         3
3                     WHITE METAL LANTERN     12472.0        Spain        -7
4                REGENCY CAKESTAND 3 TIER     12972.0       Sweden         9
...                                   ...         ...          ...       ...
1607       CREAM CUPID HEARTS COAT HANGER     12313.0       Sweden         8
1608   WHITE HANGING HEART T-LIGHT HOLDER     13029.0       France         2
1609    GLASS STAR FROSTED T-LIGHT HOLDER     15446.0  Netherlands         6
1610                   PINK CHERRY LIGHTS     12426.0      Belgium         5
1611  KNITTED UNION FLAG HOT WATER BOTTLE     13148.0      Germany        15

      UnitPrice  Revenue TransactionType  IsIdentifiedCustomer
0          3.39    50.85   Positive sale                  True
1          2.75   -35.75    Cancellation                  True
2          2.20     6.60   Positive sale                  True
3          4.07   -28.49    Cancellation                  True
4         10.20    91.80   Positive sale                  True
...         ...      ...             ...                   ...
1607       2.75    22.00   Positive sale                  True
1608       3.06     6.12   Positive sale                  True
1609       5.10    30.60   Positive sale                  True
1610       6.75    33.75   Positive sale                  True
1611       3.39    50.85   Positive sale                  True

[1612 rows x 11 columns]
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611]
Sequential index: True